version: '3'
services:
  mysql:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_PASSWORD: 123456Aa@
      MYSQL_DATABASE: ropa
      MYSQL_ROOT_HOST: '%'